from enum import Enum

class MutationMethods(Enum):
    MUT_FLIPBIT = 0
    MUT_INTERESTING8 = 1
    MUT_INTERESTING16 = 2
    MUT_INTERESTING16BE = 3
    MUT_INTERESTING32 = 4
    MUT_INTERESTING32BE = 5
    MUT_ARITH8_ = 6
    MUT_ARITH8 = 7
    MUT_ARITH16_ = 8
    MUT_ARITH16BE_ = 9
    MUT_ARITH16 = 10
    MUT_ARITH16BE = 11
    MUT_ARITH32_ = 12
    MUT_ARITH32BE_ = 13
    MUT_ARITH32 = 14
    MUT_ARITH32BE = 15
    MUT_RAND8 = 16
    MUT_CLONE_COPY = 17
    MUT_CLONE_FIXED = 18
    MUT_OVERWRITE_COPY = 19
    MUT_OVERWRITE_FIXED = 20
    MUT_BYTEADD = 21
    MUT_BYTESUB = 22
    MUT_FLIP8 = 23
    MUT_SWITCH = 24
    MUT_DEL = 25
    MUT_SHUFFLE = 26
    MUT_DELONE = 27
    MUT_INSERTONE = 28
    MUT_ASCIINUM = 29
    MUT_INSERTASCIINUM = 30
    MUT_EXTRA_OVERWRITE = 31
    MUT_EXTRA_INSERT = 32
    MUT_AUTO_EXTRA_OVERWRITE = 33
    MUT_AUTO_EXTRA_INSERT = 34
    MUT_SPLICE_OVERWRITE = 35
    MUT_SPLICE_INSERT = 36

    MUT_MAX = 37  # The maximum value of the enum

